# Generated by Django 3.0.6 on 2021-01-04 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('from_location', models.CharField(max_length=50)),
                ('to_location', models.CharField(max_length=50)),
                ('route_name', models.CharField(editable=False, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transport_type', models.CharField(choices=[('Bus', 'Travel Bus'), ('Car pooling', 'Car')], default='Bus', max_length=25)),
                ('vehicle_number', models.CharField(max_length=10, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('bus_type', models.CharField(choices=[('SL', 'Sleeper'), ('SR', 'Seater')], max_length=2)),
                ('seat_pattern', models.CharField(choices=[('BUS_1', '2+2 seater'), ('BUS_2', '2+1 seater'), ('BUS_3', '2+1 sleeper')], max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='transport.Route')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(max_length=4)),
                ('price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'available'), ('Reserved', 'reserved')], default='Available', max_length=20)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='transport.Transport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2)),
                ('age', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_users', to='transport.Seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
