# Generated by Django 3.0.6 on 2020-12-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201222_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='likes',
        ),
    ]
